/*
 * generated by Xtext
 */
package org.examplye.jvdomainmodel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.examplye.jvdomainmodel.ui.internal.DomainModelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DomainModelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DomainModelActivator.getInstance().getInjector(DomainModelActivator.ORG_EXAMPLYE_JVDOMAINMODEL_DOMAINMODEL);
	}
	
}
