/**
 * generated by Xtext
 */
package org.mph.plc.st.validation;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PlcSTValidator /* implements AbstractSTLanguageValidator  */{
}
