/*
 * generated by Xtext
 */
package org.mph.plc.st.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class STLanguageUiModule extends org.mph.plc.st.ui.AbstractSTLanguageUiModule {
	public STLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
