/*
 * generated by Xtext
 */
package org.examplye.jvdomainmodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainModelRuntimeModule extends org.examplye.jvdomainmodel.AbstractDomainModelRuntimeModule {

}
