/*
 * generated by Xtext
 */
package org.mph.plc.st;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class STLanguageRuntimeModule extends org.mph.plc.st.AbstractSTLanguageRuntimeModule {

}
