/**
 * generated by Xtext
 */
package org.mph.plc.st.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PlcSTProposalProvider /* implements AbstractSTLanguageProposalProvider  */{
}
