/*
 * generated by Xtext
 */
package org.examplye.jvdomainmodel.ui.contentassist

import org.examplye.jvdomainmodel.ui.contentassist.AbstractDomainModelProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DomainModelProposalProvider extends AbstractDomainModelProposalProvider {
}
