/*
 * generated by Xtext
 */
package org.mph.plc.st.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.mph.plc.st.ui.internal.STLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class STLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return STLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return STLanguageActivator.getInstance().getInjector(STLanguageActivator.ORG_MPH_PLC_ST_STLANGUAGE);
	}
	
}
