/*
 * generated by Xtext
 */
package org.mph.plc.st.ui.contentassist

import org.mph.plc.st.ui.contentassist.AbstractSTLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PlcSTProposalProvider extends AbstractSTLanguageProposalProvider {
}
