/*
 * generated by Xtext
 */
package org.examplye.jvdomainmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DomainModelUiModule extends org.examplye.jvdomainmodel.ui.AbstractDomainModelUiModule {
	public DomainModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
