/*
* generated by Xtext
*/
package org.mph.plc.st;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class STLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.mph.plc.st.ui.internal.STLanguageActivator.getInstance().getInjector("org.mph.plc.st.STLanguage");
	}
	
}
