package org.example.xtend;

@SuppressWarnings("all")
public class main {
  public static void main(final /* type is 'null' */ args) {
    throw new Error("Unresolved compilation problems:"
      + "\nException cannot be resolved to a type."
      + "\nException cannot be resolved to a type."
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nException cannot be resolved."
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method newIntArrayOfSize is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method join is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method newArrayList is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\n.. cannot be resolved."
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nThe method println is undefined for the type main"
      + "\nNo exception of type Exception can be thrown; an exception type must be a subclass of Throwable"
      + "\nNo exception of type Exception can be thrown; an exception type must be a subclass of Throwable"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\njoin cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\njoin cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nkeySet cannot be resolved"
      + "\njoin cannot be resolved"
      + "\n+ cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nvalues cannot be resolved"
      + "\njoin cannot be resolved"
      + "\n+ cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nadd cannot be resolved"
      + "\n+ cannot be resolved"
      + "\njoin cannot be resolved"
      + "\n+ cannot be resolved");
  }
}
