/*
* generated by Xtext
*/
package org.examplye.jvdomainmodel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.examplye.jvdomainmodel.services.DomainModelGrammarAccess;

public class DomainModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DomainModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.examplye.jvdomainmodel.parser.antlr.internal.InternalDomainModelParser createParser(XtextTokenStream stream) {
		return new org.examplye.jvdomainmodel.parser.antlr.internal.InternalDomainModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DomainModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DomainModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
