/*
* generated by Xtext
*/
package org.examplye.jvdomainmodel;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DomainModelUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.examplye.jvdomainmodel.ui.internal.DomainModelActivator.getInstance().getInjector("org.examplye.jvdomainmodel.DomainModel");
	}
	
}
